# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyLibrary copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyLibrary(object):
    def setupUi(self, MyLibrary):
        MyLibrary.setObjectName("MyLibrary")
        MyLibrary.resize(803, 525)
        self.centralwidget = QtWidgets.QWidget(MyLibrary)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 501))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 5, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 6, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 7, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.BookTable = QtWidgets.QTableView(self.widget)
        self.BookTable.setObjectName("BookTable")
        self.gridLayout.addWidget(self.BookTable, 0, 0, 1, 8)
        MyLibrary.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MyLibrary)
        self.statusbar.setObjectName("statusbar")
        MyLibrary.setStatusBar(self.statusbar)

        self.retranslateUi(MyLibrary)
        QtCore.QMetaObject.connectSlotsByName(MyLibrary)

    def retranslateUi(self, MyLibrary):
        _translate = QtCore.QCoreApplication.translate
        MyLibrary.setWindowTitle(_translate("MyLibrary", "MainWindow"))
        self.lineEdit_3.setText(_translate("MyLibrary", "Genre"))
        self.lineEdit.setText(_translate("MyLibrary", "Author"))
        self.lineEdit_4.setText(_translate("MyLibrary", "Year"))
        self.pushButton.setText(_translate("MyLibrary", "Search!"))
        self.lineEdit_2.setText(_translate("MyLibrary", "Title"))
